### ISSUE TITLE
[APP] Исправить скрипт

### ISSUE THREAD

**Issue by anry-das** [petrenkonikita112263/My_WebApp_Created_by_SpringMVC#2]
В ua.spring.app.dao.ManageDb.runScript
исправить скрипт
`SELECT COUNT(*) QUANTITY FROM all_tables WHERE owner='FIRST_OWN_DB' and TABLE_NAME like 'LAB3PN%'`
Совсем не обязательно привязывать приложение к конкретной схеме БД

**Comment by petrenkonikita112263** [comment]
Внесены исправления - a3f87c1
