### ISSUE TITLE
[APP] Проверка на null

### ISSUE THREAD

**Issue by anry-das** [petrenkonikita112263/My_WebApp_Created_by_SpringMVC#5]
В таких случаях
`int integerPropertyValue = Integer.parseInt(propertyValue);`
возможен **NumberFormatException**, например если **propertyValue** будет пустым

**Comment by petrenkonikita112263** [comment]
Проверка на null - в классах пакета dao, в методах где параметры передаються через setInt завернуть в проверку что если ничего не передается то устанавливать sql.Integer.

**Comment by petrenkonikita112263** [comment]
Дефект исправлен - a5f262c
